MODEL_REGISTRY = {
"TreeNetDenoise": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1.onnx",
        "filename": "ShadowWeightedL1.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1.pt",
        "torchfilename": "ShadowWeightedL1.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
    },
    "TreeNetDenoiseLight": {
        "url": "    https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_light.onnx",
        "filename": "ShadowWeightedL1_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_light.pt",
        "torchfilename": "ShadowWeightedL1_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
    },
    "TreeNetDenoiseSuperLight": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_super_light.onnx",
        "filename": "ShadowWeightedL1_super_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_super_light.pt",
        "torchfilename": "ShadowWeightedL1_super_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
    },
    "TreeNetDenoiseHeavy": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_24_deep_500.onnx",
        "filename": "ShadowWeightedL1_24_deep_500.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_24_deep_500.pt",
        "torchfilename": "ShadowWeightedL1_24_deep_500.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
    },
    "Deblur": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/realblur_gamma_140.onnx",
        "filename": "realblur_gamma_140.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/realblur_gamma_140.pt",
        "torchfilename": "realblur_gamma_140.pt",
        "demosaicing": "Malvar2004",
    },
    "DeepSharpen": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/Deblur_deep_24.onnx",
        "filename": "Deblur_deep_24.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/Deblur_deep_24.pt",
        "torchfilename": "Deblur_deep_24.pt",
        "demosaicing": "Malvar2004",
    },
    "TreeNetDenoiseXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.onnx",
        "filename": "xtrans_fixed_exposure_no_conditioning_400.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.pt",
        "torchfilename": "xtrans_fixed_exposure_no_conditioning_400.pt",
        "demosaicing": "rawpy",
        "conditioning": "false",
        "batch_size": 1, 
        "crop_size": 256,
        "cond_scale": 0,
    },
    "RestormerXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/restormer.onnx",
        "filename": "restormer.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/restormer.pt",
        "torchfilename": "restormer.pt",
        "demosaicing": "rawpy",
        "conditioning": "false",
        "batch_size": 1, 
    }, 
    "XFormerXTrans2": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xformer_fp16.onnx",
        "filename": "xformer_fp16.onnx",
        "demosaicing": "rawpy",
        "conditioning": "false",
        "batch_size": 1, 
    }, 

    "XFormerDenoise": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xformer_static.onnx",
        "filename": "xformer_static.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/xformer.pt",
        "torchfilename": "xformer.pt",
        "demosaicing": "rawpy",
        "conditioning": "false",
        "batch_size": 1, 
        "crop_size": 256,
    },
    
}
